In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.20.0'

In [3]:
## Creating tensor 

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
## Check number of imentions 
scalar.ndim

0

In [5]:
## Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10, 7],
                    [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) 

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]], dtype=tf.int16)

tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int16, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int16)>

In [12]:
tensor.ndim

3

In [13]:
changable_tensor = tf.Variable([1., 3])
unchangable_tensor = tf.constant([1., 3])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 3.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 3.], dtype=float32)>)

In [14]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([7., 3.], dtype=float32)>

In [15]:
## Creating random tensors
random_1 = tf.random.set_seed(23);
random_1 = tf.random.normal([4,3])
random_2 = tf.random.set_seed(23);
random_2 = tf.random.normal([4,3])

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[ 0.7354863 ,  1.0494297 ,  0.614072  ],
        [ 0.10622141,  1.4849378 , -0.03285756],
        [ 0.39278197, -1.4088944 ,  0.23070626],
        [-0.9749657 , -0.11014714, -1.1641669 ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[ 0.7354863 ,  1.0494297 ,  0.614072  ],
        [ 0.10622141,  1.4849378 , -0.03285756],
        [ 0.39278197, -1.4088944 ,  0.23070626],
        [-0.9749657 , -0.11014714, -1.1641669 ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [16]:
## Shuffle the order of element in a tensor 
not_shuffle = tf.constant([[10, 7],
                          [2, 5],
                           [6, 12]])

tf.random.set_seed(42)
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 6, 12],
       [10,  7]])>

In [17]:
## Other way to make tensor 
tf.ones(shape=(12, 10))

<tf.Tensor: shape=(12, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
tf.zeros(shape=(7, 6))

<tf.Tensor: shape=(7, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [19]:
## Creating tensor myself

ttf = tf.random.set_seed(23)
ttf = tf.random.normal(shape=(4, 5))

ts = tf.random.Generator.from_seed(23)
ts = ts.normal(shape=(4,5))
ts, ttf

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892, -1.5700307 ,  0.4457582 ,  0.10944034],
        [-0.8035768 , -1.7166729 ,  0.3738578 , -0.14371012, -0.34646833],
        [ 1.1456194 , -0.416     ,  0.43369916,  1.0241015 , -0.74785167],
        [-0.59090924, -1.2060374 ,  0.8307429 ,  1.0951619 ,  1.3672234 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 0.7354863 ,  1.0494297 ,  0.614072  ,  0.10622141,  1.4849378 ],
        [-0.03285756,  0.39278197, -1.4088944 ,  0.23070626, -0.9749657 ],
        [-0.11014714, -1.1641669 ,  0.82160586,  0.69351906, -0.08046739],
        [-0.26474208, -0.16769317,  0.00462076, -0.09378947,  1.794866  ]],
       dtype=float32)>)

In [20]:
import numpy as np 
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [21]:
tf.constant(a, shape=(2,5))

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])>

In [22]:
## Getting information from tensor 
# Shape
# Rank
# Dimension
# size

In [23]:
rank_4_tensor = tf.ones(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [24]:
rank_4_tensor[0][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
## Indexing tensor

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [26]:
## Get the first dimension from each element 
we = rank_4_tensor[:1, :1, :1, :1]

In [27]:
rank_3_tensor = rank_4_tensor[:, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 1, 3, 4, 5), dtype=float32, numpy=
array([[[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]],



       [[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]]], dtype=float32)>

In [28]:
### Manipulating tensors
## with +, -, *, and /. 

In [29]:
## matrix multiplication 
tsf = tf.constant([[10, 7], 
                   [5, 7]])

In [30]:
tf.matmul([tsf], tsf)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[135, 119],
        [ 85,  84]]])>

In [31]:
## same as 

tsf @ tsf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[135, 119],
       [ 85,  84]])>

In [32]:
tf.transpose(tsf)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 7,  7]])>

In [33]:
## Tesnor aggregation 

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50], dtype=tf.float16, seed=42)
F

<tf.Tensor: shape=(50,), dtype=float16, numpy=
array([0.3525 , 0.2207 , 0.5645 , 0.5684 , 0.996  , 0.755  , 0.7197 ,
       0.1885 , 0.791  , 0.4658 , 0.4844 , 0.914  , 0.458  , 0.741  ,
       0.06055, 0.3184 , 0.3066 , 0.753  , 0.3584 , 0.06445, 0.498  ,
       0.3887 , 0.6777 , 0.1641 , 0.2295 , 0.7217 , 0.0957 , 0.10254,
       0.2266 , 0.3408 , 0.2148 , 0.3145 , 0.701  , 0.2715 , 0.4844 ,
       0.7715 , 0.4023 , 0.8174 , 0.9746 , 0.4326 , 0.8115 , 0.332  ,
       0.6055 , 0.05273, 0.661  , 0.834  , 0.06934, 0.332  , 0.574  ,
       0.1699 ], dtype=float16)>

In [34]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float16, numpy=0.99609375>

In [35]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float16, numpy=0.99609375>

In [36]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [37]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float16, numpy=0.052734375>

In [38]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [39]:
F.ndim

1

In [41]:
tf.config.list_physical_devices()

[]

In [ ]:
!nvidia